export const products = [
  {
    id: "acepass",
    name: "AcePass",
    tagline: "Nigeria's most complete exam prep platform.",
    description: "A JAMB and Post-UTME CBT preparation platform for Nigerian secondary school students. AcePass gives students access to question banks across 26 subjects, Post-UTME simulations, offline support, and an AI study chatbot — all gated by secure access codes.",
    category: "Education",
    stack: "education",
    tag: "Exams · CBT · AI",
    color: "teal" as const,
    url: null,
    status: "live" as const,
    features: [
      "Question banks across 26 JAMB subjects",
      "Post-UTME simulation mode",
      "AI-powered study chatbot",
      "Offline-capable question access",
      "Secure access code system",
      "Performance analytics per subject",
    ],
    audience: "Nigerian secondary school students (SS3 & JAMB candidates)",
    impact: "Active users with real access codes distributed",
  },
  {
    id: "cramwiz",
    name: "CramWiz",
    tagline: "Study smarter, not harder.",
    description: "A smart learning and study acceleration platform built on Next.js with Upstash Redis for authentication and access control. CramWiz adapts to how students learn — structured, outcome-oriented, and built for the realities of Nigerian academic schedules.",
    category: "Education",
    stack: "education",
    tag: "EdTech · Learning",
    color: "teal" as const,
    url: null,
    status: "live" as const,
    features: [
      "Adaptive learning paths",
      "Smart study scheduling",
      "Subject-level progress tracking",
      "Access code authentication via Upstash Redis",
      "AI study assistance",
      "Exam-focused content modules",
    ],
    audience: "Nigerian students preparing for competitive academic milestones",
    impact: "Built on Next.js + Vercel with full user auth system",
  },
  {
    id: "bizhealth",
    name: "BizKlarity",
    tagline: "Know your business. Fix what's broken. Scale what works.",
    description: "An AI-powered SME business health audit tool designed specifically for Nigerian small and medium enterprises. BizKlarity runs businesses through a structured diagnostic across four dimensions — Financial Health, Operations, Marketing, and Growth — and returns actionable AI-generated insights via the Groq API.",
    category: "Business",
    stack: "business",
    tag: "AI · Business Intelligence",
    color: "blue" as const,
    url: null,
    status: "live" as const,
    features: [
      "4-dimension business health audit",
      "Financial Health scoring",
      "Operational efficiency analysis",
      "Marketing & brand assessment",
      "Growth readiness evaluation",
      "AI-generated action plan (Groq-powered)",
      "Shareable audit reports",
    ],
    audience: "Nigerian SME founders, operators, and business owners",
    impact: "Built on Vite + React with Vercel serverless backend hiding Groq API",
  },
  {
    id: "kraftpitch",
    name: "KraftPitch",
    tagline: "Every proposal. Every invoice. Polished and fast.",
    description: "A professional proposal and invoice builder for businesses, freelancers, and agencies. KraftPitch makes it effortless to create branded, client-ready documents — from investor pitch proposals to service invoices — with a clean, fast interface that gets out of your way.",
    category: "Business",
    stack: "business",
    tag: "Proposals · Invoices",
    color: "blue" as const,
    url: "https://kraftpitch.vercel.app/dashboard",
    status: "live" as const,
    features: [
      "Professional proposal builder",
      "Invoice generation and management",
      "Branded document templates",
      "Client-ready PDF export",
      "Dashboard for all documents",
      "Fast, distraction-free editor",
    ],
    audience: "Freelancers, agencies, consultants, and SMEs",
    impact: "Live at kraftpitch.vercel.app — deployed and active",
  },
  {
    id: "brandwella",
    name: "BrandWella",
    tagline: "Your brand, structured and scalable.",
    description: "A brand strategy and identity system platform that takes businesses from vague positioning to a clear, structured brand identity. BrandWella covers the full branding stack — from core messaging and audience definition to visual identity guidelines — making professional-grade branding accessible to growing businesses.",
    category: "Business",
    stack: "business",
    tag: "Branding · Strategy",
    color: "purple" as const,
    url: null,
    status: "coming-soon" as const,
    features: [
      "Brand positioning framework",
      "Core messaging architecture",
      "Audience persona builder",
      "Visual identity system guidelines",
      "Brand voice & tone definition",
      "Exportable brand playbook",
    ],
    audience: "Startups, SMEs, and personal brands building from scratch or rebranding",
    impact: "In development — part of the ESBRON Business Growth Stack",
  },
];

export const pillars = [
  {
    icon: "⚙",
    title: "Build Digital Products",
    description: "We conceive, design, and ship software products — from AI-powered SaaS tools to consumer platforms — with a bias toward speed, simplicity, and scalability.",
  },
  {
    icon: "↗",
    title: "Develop Brands & Growth Systems",
    description: "We build the brand infrastructure, positioning, and growth mechanics that help businesses become legible, memorable, and scalable in competitive markets.",
  },
  {
    icon: "◈",
    title: "Create Education & Media Infrastructure",
    description: "We design learning systems and media platforms that prepare people for a rapidly evolving digital economy — accessible, rigorous, and built for outcomes.",
  },
];

export const teamValues = [
  {
    title: "Build with conviction",
    description: "We don't build things because they're trendy. We build because we've identified a real gap and we're the right people to close it.",
  },
  {
    title: "Clarity over complexity",
    description: "The best product is the one that makes a hard thing feel simple. We obsess over clarity at every level — design, code, and communication.",
  },
  {
    title: "Africa-first, world-class",
    description: "Built in Port Harcourt. Designed for Nigeria. Scaled for the world. We refuse the idea that African-built means second-rate.",
  },
  {
    title: "Ship, then improve",
    description: "Perfect is the enemy of live. We deploy, learn from real users, and iterate fast. Momentum is a feature.",
  },
];
